export type Env = {
  "APP_HOST": string
  "APP_PORT": 4000,
  "APP_KEY": string
  "APP_DOMAIN": string
  "APP_HTTP_SCHEME": string
  "NODE_ENV": string
  "PROVIDER_MONGODB_DSN": string
  "PROVIDER_MYSQL_HOST": string
  "PROVIDER_MYSQL_PORT": number,
  "PROVIDER_MYSQL_USER": string
  "PROVIDER_MYSQL_PASS": string
  "PROVIDER_MYSQL_DB": string
  "PROVIDER_MYSQL_POOL_LIMIT": number,
  "PROVIDER_REDIS_DSN": string
}

export type EnvKey = 'APP_HOST'|'APP_PORT'|'APP_KEY'|'APP_DOMAIN'|'APP_HTTP_SCHEME'|'NODE_ENV'|'PROVIDER_MONGODB_DSN'|'PROVIDER_MYSQL_HOST'|'PROVIDER_MYSQL_PORT'|'PROVIDER_MYSQL_USER'|'PROVIDER_MYSQL_PASS'|'PROVIDER_MYSQL_DB'|'PROVIDER_MYSQL_POOL_LIMIT'|'PROVIDER_REDIS_DSN'